### ISSUE TITLE
packer hangs when I set the memory size to 8196 - for creating virtualbox-iso

### ISSUE THREAD

**Issue by yqian1991** [timsutton/osx-vm-templates#39]
I want to create a box by OSX Yosemite 10.10.4, 

the default memory size is 2048 in template.json, when I changed the size to 8196 and use packer to build the vbox, then packer hangs and show 
         Waiting for SSH to become available...

The GUI is just black, and nothing happened.

**Comment by timsutton** [comment]
I've heard reports from @chilcote before that he had a similar problem - at least, SSH not responsive - with VMware Fusion as well once he bumped the RAM size up to 4096.

This all seems odd, given that I can make an OS X VM manually with plenty of RAM and it functions as expected.

**Comment by chilcote** [comment]
The vmware-vmx provider seems to work irt to ssh with >2048 set.

**Comment by zigg** [comment]
This seems to be a VirtualBox problem. I can't create a straight OS X VM with 4 GB RAM either—it simply fails to boot.

**Comment by cybertk** [comment]
I fixed this by increasing vram to 128mb

```
["modifyvm", "{{.Name}}", "--vram", "128"]
```

**Comment by zigg** [comment]
I wonder if this is what was causing the problems referenced in PR #49.

**Comment by zigg** [comment]
This is a different problem than #49, but it is true that the box finishes booting if it has 4096 MB RAM *and* at least 128 MB VRAM. 64 MB VRAM didn't work. Build is still running; I'll see how that goes.

**Comment by zigg** [comment]
The above-mentioned build went fine. It did not solve the ARD problem (I'm perpetually on the lookout for a fix for that… but I digress.)

I would be okay with bumping up the VRAM to 128 MB (which is the maximum) by default, to make adjusting the RAM size less obtuse.

**Comment by timsutton** [comment]
Thanks all!
